[tool.mypy]
ignore_missing_imports = true
namespace_packages = false

[tool.ruff.lint]
# pyflakes, pycodestyle, isort
select = ["F", "E", "W", "I001", "B"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
known-third-party = ["alembic", "fastapi", "sqlalchemy"]
