services:
  app:
    container_name: monolith_app
    build:
      context: ..
      dockerfile: monolith/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../monolith:/app
    depends_on:
      - db
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]

  db:
    container_name: monolith_db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monolith_db
    ports:
      - "5432:5432"
    volumes:
      - monolith_db_data:/var/lib/postgresql/data

volumes:
  monolith_db_data:
