services:
  app:
    container_name: monolith_app
    build:
      context: ..
      dockerfile: monolith/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../monolith:/app
    command: ["fastapi", "dev", "app/main.py", "--host", "0.0.0.0", "--port", "8000"]
